version: '3.9'
services:
  oracle-xe:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PASSWORD: ${DB_PASSWORD}
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - app-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      - oracle-xe
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_NAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  oracle-data: